Migration v16
Horanet/payment_tipiregie pull request #32
Opened 2024-02-01 15:10 UTC by ylamoincl

Migration of this module to Odoo v16 proposed by [Yotech](https://www.yotech.pro).

2024-02-07 11:06 UTC, Max-282 requested changes
Beau travail ! Les modèles ont bien bougés.

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/__manifest__.py
> +    "category": "Accounting",
```suggestion
    "category": "Accounting/Payment Providers",
```
Les intermédiaires de paiements de Odoo ont tous cette catégorie

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/const.py
> +    # "pending": ["pending"],
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/controllers/main.py
> +# from odoo.addons.payment.models.payment_acquirer import ValidationError
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/controllers/main.py
> +from odoo import http, exceptions
```suggestion
from odoo import exceptions, http
```
Nous mettons dans l'ordre alphabétique par convention Horanet, cela peut s'appliquer pour l'ensemble des fichier python de ce projet

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/controllers/main.py
> +        return_url = post.pop("return_url", "/")
```suggestion
        return_url = post.pop("return_url", "/payment/process")
```
url créée par Odoo redirigeant automatiquement sur la facture avec un message type "Paiement validé"

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/controllers/main.py
> +        return ""
Pourquoi retirer les messages de retour ? Ils ne sont plus utilisés ?

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/data/cron_check_drafts.xml
> +            <field name="active" eval="False"/>
Pourquoi ne pas souhaiter l'activation de ce cron par défaut ?

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_provider.py
> +# from odoo.addons.payment.models.payment_acquirer import ValidationError
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_provider.py
> +    def _check_environment(self):
```suggestion
    def _check_payfip_state(self):
```
Rapeller "state" dans le nom de la méthode par convention  + "payfip" pour éviter d'éventuel conflit de nom (model partagé)

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_provider.py
> +
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_provider.py
> +            raise exceptions.ValidationError(_("PayFIP: activation mode can be activate in test environment only and if payment provider is published on the website."))
```suggestion
            raise exceptions.ValidationError(_("PayFIP: activation mode can be activate in test environment only."))
```
La notion de publication n'existe plus dans les provider, cela rendrait confus l'utilisateur

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_provider.py
> +        in_activation = self.filtered(lambda acquirer: acquirer.payfip_activation_mode)
```suggestion
        in_activation = self.filtered('payfip_activation_mode')
```
Tips : pas besoin de lambda si on évalue juste la présence du champ, les deux fonctionnent donc cela est à votre convenance

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_transaction.py
> +
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_transaction.py
> +    def _get_specific_rendering_values(self, processing_values):
Les surcharge de méthodes devraient être situé dans la section "region CRUD (overrides)"

Nous souhaitons suivre [les conventions d'OCA](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst)

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/models/payment_transaction.py
> +        #     self._set_pending()
```suggestion
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/static/src/img/logo_payfip.jpg
A quoi sert ce fichier ? Doublon avec l'icone de description

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/static/description/index.html
> +    <p>PayFIP est un système de paiement en ligne proposé pa la Direction générale des Finances Publiques. Son but
```suggestion
    <p>PayFIP est un système de paiement en ligne proposé par la Direction générale des Finances Publiques. Son but
```

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/views/payment_payfip_templates.xml
> +    </template> -->
Retirer ce dead code

2024-02-07 11:06 UTC, Max-282 commented on payment_payfip/views/payment_views.xml
> +    <!-- <record id="transaction_form_payfip" model="ir.ui.view">
Retirer ici aussi tout le dead code

2024-02-07 11:20 UTC, Creamaster requested changes
Merci pour le portage

2024-02-07 11:20 UTC, Creamaster commented on payment_payfip/models/payment_transaction.py
Par convention (OCA), nous essayons de nommer nos fichiers 'inherited_....' lorsqu'ils contiennent une surcharge de modèle ou une surcharge de vue. Ici cela serait `inherited_payment_transaction.py`

voir : 
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#L201

2024-02-07 11:20 UTC, Creamaster commented on payment_payfip/controllers/main.py
> +    @http.route("/payment/payfip/pay", type="http", auth="none", methods=["GET", "POST"], csrf=False)
Par convention, nous gardons les variables en simple quote et les textes en doubles quotes.

Si c'est traduit = double quotes
Si cela ne peut pas être modifié sans "casser" le fonctionnement = simple quote

```suggestion
    @http.route('/payment/payfip/pay', type='http', auth='none', methods=['GET', 'POST'], csrf=False)
```

2024-08-02 08:32 UTC, ylamoincl commented on payment_payfip/controllers/main.py
> +        return ""
Ils sont géré par `env["payment.transaction"].sudo()._handle_notification_data("payfip", post)`

2024-08-19 07:13 UTC, Max-282 approved these changes

2024-08-19 07:13 UTC, Max-282 commented on payment_payfip/i18n/fr.po
> +msgstr ""
```suggestion
msgstr "Référence de la demande de transaction telle que stockée dans la base de donnée de l'acquéreur."
```

2024-08-19 07:13 UTC, Max-282 commented on payment_payfip/i18n/fr.po
> +msgstr ""
```suggestion
msgstr "PayFIP : Paiements en brouillons réévalués"
```

2024-08-19 07:13 UTC, Max-282 commented on payment_payfip/i18n/fr.po
> +msgstr "Votre paiement a été traité avec succès. Merci!"
```suggestion
msgstr "Votre paiement a été traité avec succès. Merci !"
```

2024-11-05 13:24 UTC, Creamaster approved these changes

2024-11-05 13:26 UTC, merged